baseurl: "/students" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://htc-ccis2595.github.io/" # the base hostname & protocol for your site
title: "CCIS 2595 Java"

exclude:
  - "README.md"
  - "Gemfile"
